name: todos
description: A Baku example project.
dependencies:
  uuid: ^0.5.0
  flutter:
    path: ../../deps/flutter/packages/flutter
dev_dependencies:
  test: any
  flutter_test:
    path: ../../deps/flutter/packages/flutter_test
  flutter_driver:
    path: ../../deps/flutter/packages/flutter_driver
