name: mdtest
description: A multi-device app testing framework for Android and iOS

dependencies:
  args: ^0.13.4
  stack_trace: ^1.4.0
  coverage: ^0.7.9
  glob: ">=1.1.3"
  intl: ">=0.12.4+2"
  dlog:
    path: ../../../../third_party/dart/dlog
  flutter_driver:
    path: ../deps/flutter/packages/flutter_driver
